### ISSUE TITLE
Which folder belongs to real and fake (gan, diffusion) or miscellous?

### ISSUE THREAD

**Issue by jS5t3r** [awsaf49/artifact#3]
https://www.kaggle.com/datasets/awsaf49/artifact-dataset/discussion/410796

I was reading the paper: https://arxiv.org/pdf/2302.11970.pdf

Still I am unsure, which folder belongs to which category. My guess:

Real:
"afhq",
"celebahq",
"coco",
"ffhq",
"imagenet",
"landscape",
"lsun",
"metfaces",
"cycle_gan"

Fake - GAN:
"big_gan",
"cips",
"face_synthetics",
"gansformer",
"gau_gan",
"generative_inpainting",
"lama",
"mat",
"pro_gan",
"projected_gan",
"sfhq",
"star_gan",
"stylegan1",
"stylegan2",
"stylegan3",
"taming_transformer"

Fake - Diffusion:
"denoising_diffusion_gan",
"glide",
"latent_diffusion",
"palette",
"sfhq",
"stable_diffusion",
"vq_diffusion"

Is that correct?

**Comment by awsaf49** [comment]
Each folder contains a `metadata.csv` file which contains the relative file path of each file and their associated `label`.

**Comment by jS5t3r** [comment]
This does not answer my question. 

is sfhq created from a diffusion model? Is face_synthetics created by a GAN model? This is what I want to distinguish

**Comment by awsaf49** [comment]
My bad I only noticed the first part `Which folder belongs to real and fake`. Anyway, I hope the following answer helps,

## GAN

StyleGAN, StyleGAN2, StyleGAN3, Taming Transformer, BigGAN, CycleGAN, Denoising Diffusion GAN, GANFormer, GauGAN, ProGAN, ProjectedGAN, SFHQ, StarGAN

## Diffusion

Glide, DDPM, Denoising Diffusion GAN, Latent Diffusion, Palette, Stable Diffusion, VQ Diffusion

## Misc

Generative Inpainting (GC), CIPS, FaceSynthesis, LaMa, MAT

**Comment by jS5t3r** [comment]
Thank you very much :)
