### ISSUE TITLE
Captions for real/fake images

### ISSUE THREAD

**Issue by Rohit8y** [awsaf49/artifact#5]
Thank you for make the dataset public, it is a really big contribution to the field!

When you generate these fake images, the ones from COCO-dataset, do you also save at some place the caption of the fake image generated? I can see it is not provided in the metadata but recent [studies](https://arxiv.org/abs/2210.06998) have shown captions plays a very important role in identifying such images and my research also revolves around image+caption embedding.

 If possible can you also release the captions for these real/fake images?

**Comment by Najib-Haq** [comment]
Hi @Rohit8y, thank you for your interest in our work. But unfortunately we didn't save the captions when generating the images. So we cannot provide them.

Maybe you can use captioning tools that are available to caption the images?
