### ISSUE TITLE
How to prepare this dataset for training a neural network to detect fakes?

### ISSUE THREAD

**Issue by Dimundriy** [awsaf49/artifact#6]
Since the data is sorted by sources (and in some parks there are only real ones and in others only artificial ones), the question arises how to properly organize them for feeding into the model input. Is it necessary to shuffle the data somehow?

**Comment by Dimundriy** [comment]
Everything is clear with this. But I do not understand this: for example, I load data from one folder on cvs and there are all with target = 0, and since the dataset is large to load data from several or folders is quite difficult. As a result, my question is: how to split the dataset into several small parts, so that the net will be trained evenly and correctly.

**Comment by awsaf49** [comment]
Actually, we loaded images from multiple folders, merged all `metadata.csv` files, and then split them using `StratifiedGroupKFold` combined with `KFold` for cross-validation. Therefore, I'm not sure I can advise on how to avoid loading images from several folders.

**Comment by awsaf49** [comment]
We didn't balance the dataset. As there were enough samples per class, balancing wouldn't have made any big difference.

**Comment by Dimundriy** [comment]
I'm understood, thank you
